// Copyright (C) 2026 Tony Aly
// SPDX-License-Identifier: Apache-2.0
// One catalog for every kind of sellable value (MASTER.md §4.2, C5.09).
import { defineModule } from "@/core/module";

export default defineModule({
  name: "catalog",
  version: "0.1.0",
  requires: ["core", "cms", "invoicing", "forms"],
  tables: () => import("./tables"),
  services: () => import("./service"),
  jobs: () => import("./jobs"),
  events: {
    emits: [
      "catalog.productCreated",
      "catalog.productUpdated",
      "catalog.productActivated",
      "catalog.productArchived",
      "catalog.productRestored",
      "catalog.productVisibilityChanged",
      "catalog.optionTypeCreated",
      "catalog.productOptionAssigned",
      "catalog.variantMatrixApplied",
      "catalog.attributeDefined",
      "catalog.productMediaAttached",
      "catalog.priceListCreated",
      "catalog.productRelated",
      "catalog.bundleComponentAdded",
      "catalog.serviceOfferingConfigured",
      "catalog.priceRuleSet",
      "catalog.inventoryEnabled",
      "catalog.stockMoved",
      "catalog.stockReserved",
      "catalog.stockTransferred",
      "catalog.supplierCreated",
      "catalog.purchaseOrderPlaced",
      "catalog.purchaseOrderReceived",
      "catalog.backInStock",
      "catalog.cartOpened",
      "catalog.cartItemAdded",
      "catalog.cartAbandoned",
      "catalog.orderPlaced",
      "catalog.orderPaid",
      "catalog.orderCancelled",
      "catalog.fulfillmentCreated",
      "catalog.fulfillmentShipped",
      "catalog.fulfillmentDelivered",
      "catalog.fulfillmentFailed",
      "catalog.returnRequested",
      "catalog.returnDecided",
      "catalog.returnReceived",
      "catalog.returnRefunded",
      "catalog.couponCreated",
      "catalog.giftCardIssued",
    ],
  },
});
