// Copyright (C) 2026 Tony Aly
// SPDX-License-Identifier: AGPL-3.0-only
// The activity feed's English (MASTER.md §4.8).
//
// This is owner-facing prose generated by code, which makes it exactly the
// kind of thing that is wrong for months without anybody filing it: the feed
// rendered `cms.ensureDefaults` as "Cm — ensure defaults" because the label
// was derived by stripping a trailing s from the module name.
import { describe, expect, it } from "vitest";
import { describeAction } from "../../app/(admin)/admin/describeAction";
import { ensureDefaults } from "@/modules/cms/service";
import { mergeContacts } from "@/core/contacts/service";
import { ready } from "@/core/runtime";

describe("audit log labels", () => {
  it("says what the service says about itself", async () => {
    await ready();
    expect(describeAction("cms.ensureDefaults")).toBe(ensureDefaults.def.summary);
    expect(describeAction("contacts.merge")).toBe(mergeContacts.def.summary);
  });

  it("never mangles a module name that is not a plural noun", async () => {
    await ready();
    expect(describeAction("cms.ensureDefaults")).not.toContain("Cm ");
    // Unregistered, so this exercises the fallback rather than the summary.
    expect(describeAction("cms.somethingRemovedLaterOn")).toBe(
      "Cms — something removed later on",
    );
  });

  it("keeps history readable when the service is gone", () => {
    // Audit rows outlive the code that wrote them: a renamed or removed module
    // leaves rows naming something the registry no longer has.
    expect(describeAction("legacy.doTheThing")).toBe("Legacy — do the thing");
    expect(describeAction("not-a-service-name")).toBe("not-a-service-name");
  });
});
