// Copyright (C) 2026 Tony Aly
// SPDX-License-Identifier: Apache-2.0
// Assembled demo scenarios (MASTER.md §38, C1.27).
import type { OnboardingModuleExport } from "@/core/onboarding/contract";

const COMPLETE_MODULES = [
  "core",
  "cms",
  "forms",
  "catalog",
  "invoicing",
  "galleries",
  "quotes",
  "reporting",
  "seed",
] as const;

const COMPLETE_CAPABILITIES = [
  "demo:manage",
  "cms:view",
  "forms:view",
  "contacts:view",
  "locations:view",
  "scheduling:view",
  "crm:view",
  "catalog:view",
  "invoicing:view",
  "galleries:view",
  "quotes:view",
  "reporting:view",
] as const;

const COMPLETE_FIXTURES = [
  { key: "cms.current-modules", version: 1 },
  { key: "forms.current-modules", version: 1 },
  { key: "core.demo-contacts", version: 1 },
  { key: "core.demo-locations", version: 1 },
  { key: "core.demo-bookings", version: 1 },
  { key: "core.demo-inbox", version: 1 },
  { key: "catalog.demo-product", version: 1 },
  { key: "invoicing.demo-invoice", version: 1 },
  { key: "galleries.demo-gallery", version: 1 },
  { key: "quotes.demo-quote", version: 1 },
  { key: "reporting.demo-view", version: 1 },
] as const;

const contribution: OnboardingModuleExport = {
  targets: [
    {
      key: "seed.admin-demos",
      href: "/admin/demos",
      requiredModules: ["seed"],
      requiredCapabilities: ["demo:manage"],
    },
  ],
  guidance: [
    {
      key: "seed.creator-day",
      version: 1,
      titleKey: "guidance.flow.creatorDay.title",
      descriptionKey: "guidance.flow.creatorDay.description",
      audienceRoles: ["owner"],
      requiredCapabilities: ["*:manage"],
      status: "active",
      steps: [
        {
          key: "open-gallery",
          titleKey: "guidance.step.creatorGallery.title",
          descriptionKey: "guidance.step.creatorGallery.description",
          href: "/admin/galleries",
          requiredCapabilities: ["galleries:view"],
          outcome: { type: "audit", actions: ["galleries.create"] },
        },
        {
          key: "send-quote",
          titleKey: "guidance.step.creatorQuote.title",
          descriptionKey: "guidance.step.creatorQuote.description",
          href: "/admin/quotes",
          requiredCapabilities: ["quotes:view"],
          outcome: { type: "audit", actions: ["quotes.create"] },
        },
        {
          key: "answer-inbox",
          titleKey: "guidance.step.creatorInbox.title",
          descriptionKey: "guidance.step.creatorInbox.description",
          href: "/admin/inbox",
          requiredCapabilities: ["crm:view"],
          outcome: { type: "audit", actions: ["conversations.reply"] },
        },
      ],
    },
    {
      key: "seed.service-day",
      version: 1,
      titleKey: "guidance.flow.serviceDay.title",
      descriptionKey: "guidance.flow.serviceDay.description",
      audienceRoles: ["owner"],
      requiredCapabilities: ["*:manage"],
      status: "active",
      steps: [
        {
          key: "see-sitting",
          titleKey: "guidance.step.serviceBooking.title",
          descriptionKey: "guidance.step.serviceBooking.description",
          href: "/admin/appointments",
          requiredCapabilities: ["scheduling:view"],
          outcome: { type: "audit", actions: ["bookings.create"] },
        },
        {
          key: "chase-invoice",
          titleKey: "guidance.step.serviceInvoice.title",
          descriptionKey: "guidance.step.serviceInvoice.description",
          href: "/admin/invoices",
          requiredCapabilities: ["invoicing:view"],
          outcome: { type: "audit", actions: ["invoicing.issue"] },
        },
        {
          key: "open-quote",
          titleKey: "guidance.step.serviceQuote.title",
          descriptionKey: "guidance.step.serviceQuote.description",
          href: "/admin/quotes",
          requiredCapabilities: ["quotes:view"],
          outcome: { type: "audit", actions: ["quotes.create"] },
        },
      ],
    },
    {
      key: "seed.shop-day",
      version: 1,
      titleKey: "guidance.flow.shopDay.title",
      descriptionKey: "guidance.flow.shopDay.description",
      audienceRoles: ["owner"],
      requiredCapabilities: ["*:manage"],
      status: "active",
      steps: [
        {
          key: "see-print",
          titleKey: "guidance.step.shopProduct.title",
          descriptionKey: "guidance.step.shopProduct.description",
          href: "/admin/products",
          requiredCapabilities: ["catalog:view"],
          outcome: { type: "audit", actions: ["catalog.createProduct"] },
        },
        {
          key: "see-overdue",
          titleKey: "guidance.step.shopInvoice.title",
          descriptionKey: "guidance.step.shopInvoice.description",
          href: "/admin/invoices",
          requiredCapabilities: ["invoicing:view"],
          outcome: { type: "audit", actions: ["invoicing.issue"] },
        },
        {
          key: "open-revenue",
          titleKey: "guidance.step.shopReport.title",
          descriptionKey: "guidance.step.shopReport.description",
          href: "/admin/reports",
          requiredCapabilities: ["reporting:view"],
          outcome: { type: "audit", actions: ["reports.saveView"] },
        },
      ],
    },
    {
      key: "seed.everything-day",
      version: 1,
      titleKey: "guidance.flow.everythingDay.title",
      descriptionKey: "guidance.flow.everythingDay.description",
      audienceRoles: ["owner"],
      requiredCapabilities: ["*:manage"],
      status: "active",
      steps: [
        {
          key: "walk-contacts",
          titleKey: "guidance.step.everythingContacts.title",
          descriptionKey: "guidance.step.everythingContacts.description",
          href: "/admin/contacts",
          requiredCapabilities: ["contacts:view"],
          outcome: { type: "audit", actions: ["contacts.update"] },
        },
        {
          key: "walk-calendar",
          titleKey: "guidance.step.everythingBooking.title",
          descriptionKey: "guidance.step.everythingBooking.description",
          href: "/admin/appointments",
          requiredCapabilities: ["scheduling:view"],
          outcome: { type: "audit", actions: ["bookings.create"] },
        },
        {
          key: "walk-commerce",
          titleKey: "guidance.step.everythingCommerce.title",
          descriptionKey: "guidance.step.everythingCommerce.description",
          href: "/admin/invoices",
          requiredCapabilities: ["invoicing:view"],
          outcome: { type: "audit", actions: ["invoicing.issue"] },
        },
      ],
    },
  ],
  scenarios: [
    {
      key: "seed.current-modules",
      version: 2,
      titleKey: "demo.scenario.currentModules.title",
      descriptionKey: "demo.scenario.currentModules.description",
      preset: "foundation",
      requiredModules: ["core", "cms", "forms", "seed"],
      requiredCapabilities: ["demo:manage", "cms:view", "forms:view"],
      fixtureContributions: [
        { key: "cms.current-modules", version: 1 },
        { key: "forms.current-modules", version: 1 },
      ],
      defaultLocale: "en",
      supportedLocales: ["en", "fr", "es"],
      tourFlowKey: "core.owner-first-win",
      status: "active",
    },
    {
      key: "seed.creator",
      version: 1,
      titleKey: "demo.scenario.creator.title",
      descriptionKey: "demo.scenario.creator.description",
      preset: "creator",
      requiredModules: [...COMPLETE_MODULES],
      requiredCapabilities: [...COMPLETE_CAPABILITIES],
      fixtureContributions: [...COMPLETE_FIXTURES],
      defaultLocale: "en",
      supportedLocales: ["en", "fr", "es"],
      tourFlowKey: "seed.creator-day",
      status: "active",
    },
    {
      key: "seed.service-business",
      version: 1,
      titleKey: "demo.scenario.serviceBusiness.title",
      descriptionKey: "demo.scenario.serviceBusiness.description",
      preset: "service-business",
      requiredModules: [...COMPLETE_MODULES],
      requiredCapabilities: [...COMPLETE_CAPABILITIES],
      fixtureContributions: [...COMPLETE_FIXTURES],
      defaultLocale: "en",
      supportedLocales: ["en", "fr", "es"],
      tourFlowKey: "seed.service-day",
      status: "active",
    },
    {
      key: "seed.shop",
      version: 1,
      titleKey: "demo.scenario.shop.title",
      descriptionKey: "demo.scenario.shop.description",
      preset: "shop",
      requiredModules: [...COMPLETE_MODULES],
      requiredCapabilities: [...COMPLETE_CAPABILITIES],
      fixtureContributions: [...COMPLETE_FIXTURES],
      defaultLocale: "en",
      supportedLocales: ["en", "fr", "es"],
      tourFlowKey: "seed.shop-day",
      status: "active",
    },
    {
      key: "seed.everything",
      version: 1,
      titleKey: "demo.scenario.everything.title",
      descriptionKey: "demo.scenario.everything.description",
      preset: "everything",
      requiredModules: [...COMPLETE_MODULES],
      requiredCapabilities: [...COMPLETE_CAPABILITIES],
      fixtureContributions: [...COMPLETE_FIXTURES],
      defaultLocale: "en",
      supportedLocales: ["en", "fr", "es"],
      tourFlowKey: "seed.everything-day",
      status: "active",
    },
  ],
  fixtures: [],
};

export default contribution;
