// Copyright (C) 2026 Tony Aly
// SPDX-License-Identifier: Apache-2.0
// Core's own manifest. Core is always on (MASTER.md §3) — it has no toggle and
// no `requires` — but it declares itself the same way a feature module does,
// so the boot sequence has exactly one shape to implement and modules have a
// worked example to copy.
import { defineModule } from "@/core/module";

export default defineModule({
  name: "core",
  version: "0.1.0",
  tables: () => import("@/core/tables"),
  services: () => import("@/core/services"),
  jobs: () => import("@/core/jobs/core-jobs"),
  onboarding: () => import("@/core/onboarding"),
  events: {
    // Core listens to *everything*, once, to fan committed events out to
    // webhook subscriptions and personal notification inboxes. It goes through the ordinary manifest
    // mechanism rather than a special case in boot, so the listener shows up
    // in the boot report like any other.
    listens: { "*": "onAnyEvent" },
    emits: [
      "contact.created",
      "contact.merged",
      "contact.mergeUndone",
      "settings.businessUpdated",
      "settings.setupCompleted",
      "module.enabled",
      "module.disabled",
      "location.created",
      "location.updated",
      "location.deleted",
      "apikey.created",
      "apikey.revoked",
      "webhook.created",
      "webhook.updated",
      "webhook.deleted",
      "agent.connected",
      "agent.hired",
      "agent.updated",
      "agent.allPaused",
      "agent.allResumed",
      "agentTask.created",
      "agentTask.assigned",
      "agentTask.cancelled",
      "agentTask.claimed",
      "agentTask.completed",
      "agentTask.failed",
      "connection.recorded",
      "connection.updated",
      "connection.removed",
      "connection.needsAttention",
      "connection.rotated",
      "mail.senderConnected",
      "mail.senderRegistered",
      "mail.senderVerified",
      "mail.defaultSenderChanged",
      "mail.senderUpdated",
      "mail.testSent",
      "mail.suppressionReleased",
      "mail.deliveryUpdated",
      "role.created",
      "role.updated",
      "role.deleted",
      "role.assigned",
      "staffInvitation.created",
      "staffInvitation.resent",
      "staffInvitation.revoked",
      "staffInvitation.accepted",
      "auth.sessionRevoked",
      "auth.otherSessionsRevoked",
      "contact.magicLinkRequested",
      "contact.portalAccountLinked",
      "contact.magicLinkSignedIn",
      "contact.lifecycleChanged",
      "contact.relationshipAdded",
      "contact.relationshipUpdated",
      "contact.relationshipRemoved",
      "contact.consentChanged",
      "contact.dataRequestSubmitted",
      "contact.dataRequestVerified",
      "contact.dataRequestCompleted",
      "contact.dataErased",
      "job.cancelled",
      "job.retried",
      "job.deadLettersRedriven",
      "outbox.replayed",
      "media.uploaded",
      "media.captureStarted",
      "media.captureLinkCreated",
      "media.captureAttached",
      "media.captureConfirmed",
      "media.captureDiscarded",
      "media.trashed",
      "media.restored",
      "media.purged",
      "media.scanned",
      "media.altTextSuggested",
      "media.altTextAccepted",
      "media.altTextDismissed",
    ],
  },
});
