// Copyright (C) 2026 Tony Aly
// SPDX-License-Identifier: Apache-2.0
// Durable owner-facing builder proposals (MASTER.md §37, C4.19).
import { sql } from "drizzle-orm";
import { check, index, integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { createdAtColumn, updatedAtColumn } from "@/core/db/columns";

export const builderProposals = pgTable(
  "builder_proposals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brief: text("brief").notNull(),
    lane: text("lane", { enum: ["structure", "vocabulary", "refused"] }).notNull(),
    status: text("status", {
      enum: ["ready", "applied", "rejected", "stale", "rolled_back"],
    }).notNull().default("ready"),
    summary: text("summary").notNull(),
    rationale: text("rationale").notNull(),
    /** Exact site state the model saw; data, never instructions. */
    baseSnapshot: jsonb("base_snapshot").notNull(),
    /** Validated service-layer operations, never SQL or arbitrary tool calls. */
    changes: jsonb("changes").notNull().default([]),
    /** Owner-readable before/after projection generated by trusted code. */
    diff: jsonb("diff").notNull().default([]),
    /** Applied ids/timestamps plus the rollback snapshot. */
    applyResult: jsonb("apply_result").notNull().default({}),
    model: text("model").notNull(),
    provider: text("provider"),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    totalTokens: integer("total_tokens").notNull().default(0),
    createdByActor: text("created_by_actor").notNull(),
    appliedAt: timestamp("applied_at", { withTimezone: true }),
    rolledBackAt: timestamp("rolled_back_at", { withTimezone: true }),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    index("builder_proposals_status_idx").on(table.status, table.createdAt),
    index("builder_proposals_created_idx").on(table.createdAt),
    check(
      "builder_proposals_lane_valid",
      sql`${table.lane} in ('structure','vocabulary','refused')`,
    ),
    check(
      "builder_proposals_status_valid",
      sql`${table.status} in ('ready','applied','rejected','stale','rolled_back')`,
    ),
    check(
      "builder_proposals_usage_valid",
      sql`${table.inputTokens} >= 0 and ${table.outputTokens} >= 0 and ${table.totalTokens} >= ${table.inputTokens} + ${table.outputTokens}`,
    ),
    check(
      "builder_proposals_changes_valid",
      sql`jsonb_typeof(${table.changes}) = 'array' and (${table.lane} = 'structure' or jsonb_array_length(${table.changes}) = 0)`,
    ),
    check(
      "builder_proposals_lifecycle_valid",
      sql`(${table.status} <> 'applied' or ${table.appliedAt} is not null) and (${table.status} <> 'rolled_back' or (${table.appliedAt} is not null and ${table.rolledBackAt} is not null))`,
    ),
  ],
);

/**
 * A code-lane proposal (MASTER.md §37, C4.20).
 *
 * Separate from `builder_proposals` because the two lanes differ in the thing
 * that matters most: a structure proposal is a list of service calls this
 * instance will make, and a code proposal is a set of files this instance will
 * never run. Sharing one table would mean one `changes` column meaning two
 * incompatible things, and a check constraint apologising for it.
 *
 * The files live here as data and are handed to the owner's repository. §37:
 * "the instance does not compile code on the box that serves traffic."
 */
export const builderCodeProposals = pgTable(
  "builder_code_proposals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brief: text("brief").notNull(),
    /** Lowercase, hyphenated; the directory everything is confined to. */
    pluginName: text("plugin_name").notNull(),
    status: text("status", {
      enum: ["ready", "refused", "delivered", "rejected"],
    })
      .notNull()
      .default("ready"),
    summary: text("summary").notNull(),
    rationale: text("rationale").notNull(),
    /** `[{ path, contents }]`, every path under `plugins/<name>/`. */
    files: jsonb("files").notNull().default([]),
    /** Every gate and its verdict, so a refusal is readable months later. */
    gates: jsonb("gates").notNull().default([]),
    /** File list, sizes and the permissions the plugin asks for. */
    diff: jsonb("diff").notNull().default({}),
    /** Where it went, when it went: a pull request or an exported patch. */
    deliveredAs: text("delivered_as", { enum: ["pull_request", "patch"] }),
    pullRequestUrl: text("pull_request_url"),
    branch: text("branch"),
    refusalReason: text("refusal_reason"),
    model: text("model").notNull(),
    provider: text("provider"),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    totalTokens: integer("total_tokens").notNull().default(0),
    createdByActor: text("created_by_actor").notNull(),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    index("builder_code_proposals_status_idx").on(table.status, table.createdAt),
    check(
      "builder_code_proposals_status_valid",
      sql`${table.status} in ('ready','refused','delivered','rejected')`,
    ),
    // A refusal says why, and a delivery says where. Neither is optional,
    // because a row that recorded one without the other would be a proposal
    // nobody can account for.
    check(
      "builder_code_proposals_refusal_reason",
      sql`${table.status} <> 'refused' or ${table.refusalReason} is not null`,
    ),
    check(
      "builder_code_proposals_delivery",
      sql`${table.status} <> 'delivered'
          or (${table.deliveredAs} is not null and ${table.deliveredAt} is not null)`,
    ),
    check(
      "builder_code_proposals_usage_valid",
      sql`${table.inputTokens} >= 0 and ${table.outputTokens} >= 0`,
    ),
    check("builder_code_proposals_files_valid", sql`jsonb_typeof(${table.files}) = 'array'`),
  ],
);
